[package]
name = "bias-vulhunt-grpc"
version = "1.0.0"
edition = "2024"
authors = [
  "Sam L. Thomas <sam@binarly.io>",
  "Francesco Evangelista <francesco@binarly.io>",
  "Yegor Vasilenko <yegor@binarly.io>",
  "Fabio Pagani <fabio@binarly.io>",
  "Fernando Mercês <fernando@binarly.io>",
  "Anton Ivanov <anton@binarly.io>",
  "Lukas Seidel <lukas@binarly.io>",
  "Claudiu-Vlad Ursache <claudiuv@binarly.io>",
  "Chris McMahon Stone <chris@binarly.io>",
]
description = "VulHunt gRPC server"
repository = "https://github.com/vulhunt-re/vulhunt"
license = "GPL-3.0"
readme = "../README.md"

[features]
default = []
bndb = ["bias-vulhunt-engine/bndb"]

[dependencies]
bias = { version = "1.0", path = "../bias" }
bias-core = { version = "1.0", path = "../bias-core", features = ["decompiler"] }
bias-vulhunt-engine = { version = "1.0", path = "../bias-vulhunt-engine" }
prost = "0.14"
prost-wkt-types = "0.7"
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tonic = "0.14"
tonic-prost = "0.14"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
uuid = { version = "1", features = ["v7"] }

[build-dependencies]
tonic-prost-build = "0.14"

[lints]
workspace = true
