[package]
name = "bias-tutil"
version = "1.0.0"
edition = "2024"
authors = [
  "Sam L. Thomas <sam@binarly.io>",
  "Francesco Evangelista <francesco@binarly.io>",
  "Yegor Vasilenko <yegor@binarly.io>",
  "Fabio Pagani <fabio@binarly.io>",
  "Fernando Mercês <fernando@binarly.io>",
  "Anton Ivanov <anton@binarly.io>",
  "Lukas Seidel <lukas@binarly.io>",
  "Claudiu-Vlad Ursache <claudiuv@binarly.io>",
  "Chris McMahon Stone <chris@binarly.io>",
]

[[bin]]
name = "bias-tutil"
path = "src/main.rs"

[dependencies]
anyhow = "1"
bias-core = { version = "1.0", path = "../bias-core", features = ["import-c"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = { version = "0.0.17", package = "serde-saphyr" }
tracing = { version = "0.1", features = ["release_max_level_warn"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
walkdir = "2"
